feat(fedd): implemented infinite scroll to the feed.
rosostolato/ipm-app pull request #101
Opened 2024-02-29 11:03 UTC by murosfc

Closes #56

2024-02-29 14:47 UTC, rosostolato requested changes
Good job! The next step is to implement the firebase function pagination. We can schedule a meeting to teach you how to use it.

2024-02-29 14:47 UTC, rosostolato commented on src/app/boletim/boletim-page.component.scss
> +    .post {
**issue**: was it a mistake?

2024-02-29 14:47 UTC, rosostolato commented on src/app/core/state/feed.store.ts
> +    onInit({ nextFeedPage: nextFeedPage }) {
**nitpick**: remove duplicate name

2024-02-29 14:47 UTC, rosostolato commented on src/app/core/state/feed.store.ts
> +    ({ startIndex, muted, ...store }, functions = inject(Functions)) => ({
**nitpick**: sort props

2024-02-29 14:47 UTC, rosostolato commented on src/app/core/state/feed.store.ts
> +        patchState(store, setSynchronized(), setEntities(slicedEntities));
**question**: I see what you did, but since we are already loading all data at once, we should have kept it in the store and created a computed value that would filter the entities by the length of the page.

But the fact is that we need to update the Firebase function to support the pagination. At least, it was a good workaround to allow you to test the infinite scroll ui.

2024-02-29 14:47 UTC, rosostolato commented on src/app/feed/feed-page.component.ts
> +        }
**nitpick**: not used

2024-02-29 14:47 UTC, rosostolato commented on src/app/feed/feed-page.component.ts
> +    CdkVirtualScrollViewport,
**nitpick**: the `ScrollingModule` already exports the `CdkVirtualScrollViewport`, I think. No need to import it again.

2024-02-29 14:47 UTC, rosostolato commented on src/app/feed/feed-page.component.ts
> +  private FEED_PAGE_SIZE = 3;
**nitpick**: to keep consistency, don't declare CAPITAL_CASE props within the class. That case is used to declare a file scoped variable, like a global var.

2024-02-29 14:47 UTC, rosostolato commented on src/app/feed/feed-post.component.ts
> +        class="message"
**nitpik**: sort props and leave binding props to the end and use the `[class.name]` syntax.

```suggestion
        class="message"
        [class.expanded]="isExpanded"
```

2024-02-29 14:47 UTC, rosostolato commented on src/app/feed/feed-post.component.ts
> +        <a (click)="toggleText()" tabindex="2">
**issue**: anchor (<a>) are only used with link urls. Use button instead.

2024-02-29 14:47 UTC, rosostolato commented on src/app/feed/feed-post.component.ts
> +    CommonModule,
**issue**: don't import the `CommonModule`, always prefer to import the directives or pipes you need individually.

2024-02-29 14:47 UTC, rosostolato commented on src/app/feed/feed-post.component.ts
> +  }
**nitpick**: declare methods in alphabetical order, move this to be after `openFacebook`

2024-02-29 19:06 UTC, murosfc commented on src/app/boletim/boletim-page.component.scss
> +    .post {
yes. Restored!

2024-02-29 19:07 UTC, murosfc commented on src/app/core/state/feed.store.ts
> +        patchState(store, setSynchronized(), setEntities(slicedEntities));
Ok. Store restored as it was.

2024-02-29 19:11 UTC, murosfc commented on src/app/feed/feed-page.component.ts
> +        }
ops, removed!

2024-02-29 19:12 UTC, murosfc commented on src/app/feed/feed-page.component.ts
> +  private FEED_PAGE_SIZE = 3;
removed for now.

2024-02-29 19:28 UTC, murosfc commented on src/app/feed/feed-post.component.ts
> +        <a (click)="toggleText()" tabindex="2">
Ok, changed!

2024-02-29 19:36 UTC, murosfc commented on src/app/core/state/feed.store.ts
> +    onInit({ nextFeedPage: nextFeedPage }) {
ops, removed since feedstore was restored back to original

2024-03-05 12:21 UTC, murosfc commented
I was afraid of upload funcions on Firebase so as not mess the current app, I was not able to test.
If you could please...
variables name using the same as documentation: https://developers.facebook.com/docs/graph-api/results/

2024-03-05 22:01 UTC, rosostolato approved these changes

2024-03-05 22:16 UTC, merged