refactor(close-button): added nav-bar back button.
rosostolato/ipm-app pull request #48
Opened 2024-02-09 00:20 UTC by murosfc

added nav-bar back button to the pages where the menu is not displayed.

I didn't like the results, I also think that those pages you'd better close the page instead of going back. If you are changing password and you regret because you recall the password, and you go back you will be redirected to the page where you input the verification code, if you back again then you will see the page where you input your phone number, does not look safe...

2024-02-12 13:58 UTC, rosostolato requested changes
I agree with you about the back button. Let's add an input prop to the `Navbar` component to allow us to inform the `href` of the back button. Then we can make it go to home, for example, by passing `/`, or login by passing `/login`.

2024-02-12 13:58 UTC, rosostolato commented on src/app/authentication/change-password-page/change-password-page.component.html
> +  <p>Preencha os campos abaixo para configurar uma nova senha para sua conta</p>
**praise**: good catch!

2024-02-12 13:58 UTC, rosostolato commented on src/app/authentication/change-password-page/change-password-page.component.ts
> +    ButtonDirective,
**praise**: good usage of the code patterns. Thanks!

2024-02-12 23:08 UTC, murosfc commented
Changed as suggested. Now we can pass the route and also ask for logout. the default route remains unchanged (go back).

2024-02-19 21:14 UTC, rosostolato approved these changes

2024-02-19 21:14 UTC, merged