feat(terms-and-policy): Added terms of use and privacy policy pages
rosostolato/ipm-app pull request #51
Opened 2024-02-12 19:45 UTC by murosfc

Closes #12 

I have created another branch form master to make sure it was clean.
Created both terms and privacy pages also adding the app-navbar to allow user to go back.

2024-02-12 19:59 UTC, rosostolato requested changes
Just one quick change request

2024-02-12 19:59 UTC, rosostolato commented on src/app/authentication/signup-page/signup-page.component.html
> +    <a href="privacy-policy">política de privacidade</a>.
**issue**: need to user angular `RouterLink` to prevent page rerendering.

2024-02-12 20:08 UTC, murosfc commented on src/app/authentication/signup-page/signup-page.component.html
> +    <a href="privacy-policy">política de privacidade</a>.
Done!

2024-02-14 22:15 UTC, rosostolato approved these changes

2024-02-14 22:15 UTC, merged