feat(popup): added a popup component
rosostolato/ipm-app pull request #71
Opened 2024-02-17 17:28 UTC by murosfc

Closes #61 

The popup component can be customized when called with the following data (url, title, message, width and height).

2024-02-18 17:06 UTC, murosfc commented
@rosostolato updated to Angular cdk

2024-02-19 12:58 UTC, rosostolato requested changes
.Asked for small changes

2024-02-19 12:58 UTC, rosostolato commented on src/app/feed/feed-post.component.ts
> +        url: this.post().permalink_url,
Remove url

2024-02-19 12:58 UTC, rosostolato commented on src/app/feed/skeleton-feed-post.component.ts
??

2024-02-23 02:40 UTC, murosfc commented on package.json
> +    "@angular/material": "^17.2.0",
done!

2024-02-23 02:40 UTC, murosfc commented on src/app/core/components/popup.component.ts
> +    this.dialogRef.close(confirmed ? this.data.url : undefined);
forgot to remove after testing

2024-02-23 02:41 UTC, murosfc commented on src/app/core/components/popup.component.ts
> +  imports: [ButtonDirective, FormsModule],
forgot to remove after changing

2024-02-23 02:41 UTC, murosfc commented on src/app/feed/feed-post.component.ts
> +  readonly dialog = inject(Dialog);
my bad!

2024-02-23 02:42 UTC, murosfc commented on src/app/feed/skeleton-feed-post.component.ts
?? lol

2024-02-23 20:31 UTC, rosostolato approved these changes

2024-02-23 20:32 UTC, merged