fix(change-password): fixed bug that made change password not work
rosostolato/ipm-app pull request #87
Opened 2024-02-24 14:25 UTC by murosfc

closes #55

2024-02-28 20:30 UTC, rosostolato requested changes

2024-02-28 20:30 UTC, rosostolato commented on src/app/authentication/change-password-page/change-password-page.component.ts
> +    });
Create form validators instead

2024-02-28 22:08 UTC, murosfc commented
form validators is there since always. 
Removed live UI validators in order to close the issue and fix the bug.
The UI thing can be done other time.

2024-03-01 16:53 UTC, rosostolato approved these changes
Lgtm

2024-03-01 16:54 UTC, merged